# rangevoting

This package simulates the counting of votes in a costituency where the STAR System (Score Then Automatic Runoff) is used, in the context of Range Voting procedure.

# Dependencies

Please notice that packages "foreach", "doParallel" and "plotly" are required.

# Installation and usage

'''{r qplot, fig.width=4, fig.height=3, message=FALSE}
devtools::install_github('unimi-dse/1a62ddfc')

require(rangevoting)
'''

# Dataset and randomvote function

The package already provides a CSV file containing votes for a costituency, but it may be substituted with any file created with function '''{r} randomvote(N,candidates,parties)'''.

# majority function

This function reads a csv file containing votes and computes the winner of that costituency in a majority system using the STAR System.
'''{r qplot, fig.width=4, fig.height=3,message=FALSE}
list(elected,counter) = majority(elected,counter)
'''

# proportional function
This function reads a csv file containing votes for each party in a costituency and assigns the corresponding number of seats, given the total seats assigned to that costituency as an input.
'''{r qplot, fig.width=4, fig.height=3,message=FALSE}
counter = proportional(seats,counter)
'''

# votehist function
This function reads a csv file containing votes for each party in a costituency and plots the overlaid histogram of votes.
'''{r qplot, fig.width=4, fig.height=3,message=FALSE}
votehist()
'''
